export const matches_played_data = {
  angle: 0,
  yDomain: [50, 90],
  color: ["#19a58a", "#e7f6f3"],
  label: ["year", "no. of matches played"],
  data: [
    { x: "2017", y: 58 },
    { x: "2008", y: 57 },
    { x: "2009", y: 56 },
    { x: "2010", y: 59 },
    { x: "2011", y: 72 },
    { x: "2012", y: 73 },
    { x: "2013", y: 75 },
    { x: "2014", y: 59 },
    { x: "2015", y: 58 },
    { x: "2016", y: 59 },
  ],
};
export const initial_data = {
  angle: 0,
  yDomain: [30, 90],
  color: ["#19a58a", "#e7f6f3"],
  label: ["loading..", "loading.."],
  data: [
    { x: "2017", y: 50 },
    { x: "2008", y: 50 },
    { x: "2009", y: 50 },
    { x: "2010", y: 50 },
    { x: "2011", y: 50 },
    { x: "2012", y: 50 },
    { x: "2013", y: 50 },
    { x: "2014", y: 50 },
    { x: "2015", y: 50 },
    { x: "2016", y: 50 },
  ],
};
export const matches_at_each_venue_data = {
  angle: 1,
  yDomain: [1, 70],
  color: ["#ff8c60", "#fff4f0"],
  label: ["name of stadium", "number of matches conducted"],
  data: [
    { x: '"Rajiv Gandhi International Stadium', y: 48 },
    { x: "Maharashtra Cricket Association Stadium", y: 14 },
    { x: "Saurashtra Cricket Association Stadium", y: 9 },
    { x: "Holkar Cricket Stadium", y: 4 },
    { x: "M Chinnaswamy Stadium", y: 65 },
    { x: "Wankhede Stadium", y: 56 },
    { x: "Eden Gardens", y: 60 },
    { x: "Feroz Shah Kotla", y: 59 },
    { x: '"Punjab Cricket Association IS Bindra Stadium', y: 10 },
    { x: "Green Park", y: 3 },
    { x: '"Punjab Cricket Association Stadium', y: 34 },
    { x: "Sawai Mansingh Stadium", y: 32 },
    { x: '"MA Chidambaram Stadium', y: 47 },
    { x: "Dr DY Patil Sports Academy", y: 16 },
    { x: "Newlands", y: 6 },
    { x: "St George's Park", y: 6 },
    { x: "Kingsmead", y: 14 },
    { x: "SuperSport Park", y: 11 },
    { x: "Buffalo Park", y: 2 },
    { x: "New Wanderers Stadium", y: 7 },
    { x: "De Beers Diamond Oval", y: 2 },
    { x: "OUTsurance Oval", y: 1 },
    { x: "Brabourne Stadium", y: 10 },
    { x: '"Sardar Patel Stadium', y: 11 },
    { x: "Barabati Stadium", y: 6 },
    { x: '"Vidarbha Cricket Association Stadium', y: 2 },
    { x: "Himachal Pradesh Cricket Association Stadium", y: 8 },
    { x: "Nehru Stadium", y: 4 },
    { x: "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium", y: 10 },
    { x: "Subrata Roy Sahara Stadium", y: 16 },
    { x: "Shaheed Veer Narayan Singh International Stadium", y: 5 },
    { x: "JSCA International Stadium Complex", y: 6 },
    { x: "Sheikh Zayed Stadium", y: 6 },
    { x: "Sharjah Cricket Stadium", y: 5 },
    { x: "Dubai International Cricket Stadium", y: 6 },
  ],
};
export const matches_at_city_data = {
  angle: 1,
  yDomain: [1, 90],
  color: ["#fecc8c", "#fffaf4"],
  label: ["city", "no. of matches played"],
  data: [
    { x: "Hyderabad", y: 48 },
    { x: "Pune", y: 31 },
    { x: "Rajkot", y: 9 },
    { x: "Indore", y: 4 },
    { x: "Bangalore", y: 65 },
    { x: "Mumbai", y: 84 },
    { x: "Kolkata", y: 60 },
    { x: "Delhi", y: 59 },
    { x: "Chandigarh", y: 45 },
    { x: "Kanpur", y: 3 },
    { x: "Jaipur", y: 32 },
    { x: "Chennai", y: 47 },
    { x: "Cape Town", y: 6 },
    { x: "Port Elizabeth", y: 6 },
    { x: "Durban", y: 14 },
    { x: "Centurion", y: 11 },
    { x: "East London", y: 2 },
    { x: "Johannesburg", y: 7 },
    { x: "Kimberley", y: 2 },
    { x: "Bloemfontein", y: 1 },
    { x: "Ahmedabad", y: 11 },
    { x: "Cuttack", y: 6 },
    { x: "Nagpur", y: 2 },
    { x: "Dharamsala", y: 8 },
    { x: "Kochi", y: 4 },
    { x: "Visakhapatnam", y: 10 },
    { x: "Raipur", y: 5 },
    { x: "Ranchi", y: 6 },
    { x: "Abu Dhabi", y: 6 },
    { x: "Sharjah", y: 5 },
  ],
};
export const matches_played_by_team_data = {
  angle: 1,
  yDomain: [10, 170],
  color: ["#d07475", "#fcf0f0"],
  label: ["team", "no. of matches played"],
  data: [
    { x: "Sunrisers Hyderabad", y: 75 },
    { x: "Royal Challengers Bangalore", y: 151 },
    { x: "Mumbai Indians", y: 156 },
    { x: "Rising Pune Supergiant", y: 15 },
    { x: "Gujarat Lions", y: 29 },
    { x: "Kolkata Knight Riders", y: 147 },
    { x: "Kings XI Punjab", y: 147 },
    { x: "Delhi Daredevils", y: 146 },
    { x: "Chennai Super Kings", y: 130 },
    { x: "Rajasthan Royals", y: 117 },
    { x: "Deccan Chargers", y: 74 },
    { x: "Kochi Tuskers Kerala", y: 13 },
    { x: "Pune Warriors", y: 45 },
    { x: "Rising Pune Supergiants", y: 13 },
  ],
};
export const matches_win_by_team_data = [
  { x: "Sunrisers Hyderabad", y: 41 },
  { x: "Rising Pune Supergiant", y: 9 },
  { x: "Kolkata Knight Riders", y: 76 },
  { x: "Kings XI Punjab", y: 69 },
  { x: "Royal Challengers Bangalore", y: 72 },
  { x: "Mumbai Indians", y: 91 },
  { x: "Delhi Daredevils", y: 61 },
  { x: "Gujarat Lions", y: 12 },
  { x: "Chennai Super Kings", y: 78 },
  { x: "Rajasthan Royals", y: 62 },
  { x: "Deccan Chargers", y: 28 },
  { x: "Pune Warriors", y: 11 },
  { x: "Kochi Tuskers Kerala", y: 5 },
  { x: "", y: 2 },
  { x: "Rising Pune Supergiants", y: 4 },
];
